name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Svelte Check
        run: bun run check

      - name: Lint
        run: bun run lint

  # Publish:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     id-token: write # The OIDC ID token is used for authentication with JSR.
  #   needs: CI
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2

  #     - name: Install dependencies
  #       run: bun install

  #     - name: Build
  #       run: bun run build:lib

  #     - name: Publish to jsr
  #       run: bun x jsr publish
