name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.3.5'

      - name: Install dependencies
        run: deno install

      - name: Svelte Check
        run: deno run check

      - name: Lint
        run: deno run lint

  # Publish:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     id-token: write # The OIDC ID token is used for authentication with JSR.
  #   needs: CI
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Deno
  #       uses: denoland/setup-deno@v2
  #       with:
  #         deno-version: 'lts'
  #     - name: Install dependencies
  #       run: deno install

  #     - name: Build
  #       run: deno run build

  #     - name: Publish to jsr
  #       run: deno run publish
