name: Publish

on:
  push:
    branches: ['main']
    paths:
      - 'src/lib/**'
      - 'package.json'
      - 'bun.lockb'
      - '.releaserc.json'
      - 'svelte.config.js'
      - 'vite.config.js'
      - 'README.md'
      - '.github/workflows/Publish.yml'

  # release:
  #   types: [created]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: github.actor == 'fanboykun' && github.repository == 'fanboykun/svelte-common-hooks'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup npm authentication
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo $NPM_TOKEN
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Setup Bun for packing
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Svelte Check
        run: bun run check

      - name: Lint
        run: bun run lint

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version package'
          title: 'chore(release): version package'
          publish: 'bun run release'
          version: 'bun run version'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
