name: Release

on:
  push:
    branches: ['main']
    paths:
      - 'src/lib/**'
      - 'package.json'
      - 'bun.lockb'
      - '.releaserc.json'
      - 'svelte.config.js'
      - 'vite.config.js'
      - 'README.md'
      - '.github/workflows/Release.yml'

  # release:
  #   types: [created]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # if: github.actor == 'fanboykun'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup npm authentication
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo $NPM_TOKEN
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Setup Node.js (for npm publishing)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun for packing
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: npm install

      - name: Svelte Check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Prepack
        run: npm run prepack

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: npx semantic-release
